# Generated by Django 6.1.1 on 2026-09-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
