# Generated by Django 5.2.17 on 2026-10-07 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeruser_role'),
        ('mfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_fraud', models.BooleanField()),
                ('source', models.CharField(default='HUMAN_REVIEW', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('labeled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth', to='mfs.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

