# Generated by Django 5.2.17 on 2026-10-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeruser_role'),
        ('mfs', '0002_transactionlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('metrics', models.JSONField(default=dict)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('generated_by', models.CharField(default='SYSTEM', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
    ]

