# Generated by Django 6.1.1 on 2026-09-24 03:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.TextField(unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('revocation_reason', models.CharField(blank=True, choices=[('PAYMENT_DEFAULT', 'Payment default'), ('CHARGEBACK', 'Chargeback'), ('FRAUD', 'Fraud'), ('SUBSCRIPTION_CANCELLED', 'Subscription cancelled'), ('ADMINISTRATIVE_ACTION', 'Administrative action')], default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='plans.plan')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='licenses.license')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
