# Generated by Django 6.1.1 on 2026-10-03 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_customeruser_email_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NO_DATA', 'No data'), ('ERROR', 'Error')], default='OK', max_length=10)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('trend', models.JSONField(blank=True, default=dict, null=True)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('insight_text', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_reports', to='accounts.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
